"use client";

import { alpha } from "@mui/material/styles";

export const DARK_GREEN = "#113E18";

export const SX = {
  section: {
    width: "100%",
    height: "100%",
    minHeight: "100%",
    position: "relative",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    pt: { xs: "calc(12px + env(safe-area-inset-top))", md: 0 },
    pb: { xs: "calc(82px + env(safe-area-inset-bottom))", md: 0 },
    px: 0,
    background: "#57bc53",
    overflow: "hidden",
    "&::after": {
      content: '""',
      position: "absolute",
      left: 0,
      right: 0,
      bottom: "calc(-1 * env(safe-area-inset-bottom))",
      height: "calc(32px + env(safe-area-inset-bottom))",
      background: "#57bc53",
      pointerEvents: "none",
    },
  },
  backdrop: {
    position: "absolute",
    inset: 0,
    pointerEvents: "none",
    opacity: 0.1,
    backgroundImage:
      "radial-gradient(circle at 60% 30%, rgba(232,255,226,0.1) 0%, transparent 24%), radial-gradient(circle at 78% 72%, rgba(232,255,226,0.08) 0%, transparent 22%)",
  },
  shell: {
    position: "relative",
    zIndex: 1,
    width: "100%",
    height: "100%",
    minHeight: "100%",
    maxWidth: 1440,
    display: "flex",
    alignItems: { xs: "stretch", md: "center" },
    justifyContent: "center",
    pointerEvents: "none",
    px: { xs: 1.15, sm: 2, md: 4 },
  },
  panel: {
    p: { xs: 0.7, sm: 1.45, md: 2.2 },
    display: "grid",
    gap: { xs: 1.05, md: 3.2 },
    gridTemplateColumns: { xs: "1fr", lg: "minmax(0, 1.04fr) minmax(360px, 0.76fr)" },
    alignItems: { xs: "start", md: "center" },
    alignContent: { xs: "center", md: "center" },
    width: "100%",
    height: "100%",
    minHeight: "100%",
    borderRadius: 0,
    background: "transparent",
    border: "none",
    boxShadow: "none",
    overflow: "hidden",
  },
  copyPanel: {
    position: "relative",
    pointerEvents: "auto",
    px: { xs: 0.2, sm: 1.2, md: 2.1 },
    py: { xs: 0.2, md: 2.8 },
    alignSelf: "center",
    justifySelf: "center",
    width: "100%",
    maxWidth: 980,
  },
  copyInner: {
    position: "relative",
    zIndex: 1,
    borderRadius: { xs: 4, md: 5 },
    background: "rgba(237,255,233,0.06)",
    border: "1px solid rgba(237,255,233,0.09)",
    padding: "clamp(0.82rem, 0.7rem + 0.5vw, 2.1rem)",
    paddingRight: {
      xs: "clamp(0.82rem, 0.7rem + 0.5vw, 1rem)",
      md: "clamp(1.4rem, 1.15rem + 1vw, 2.8rem)",
    },
  },
  kicker: {
    fontSize: { xs: "0.62rem", md: "0.74rem" },
    fontWeight: 900,
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    color: "#EDFFE8",
    mb: 1.2,
  },
  title: {
    fontWeight: 900,
    letterSpacing: "-0.03em",
    fontSize: { xs: "1.46rem", sm: "2.2rem", md: "3.38rem" },
    lineHeight: 0.94,
    color: "#F7FFF4",
    maxWidth: 760,
  },
  titleLine: {
    display: "block",
  },
  titleLineWithRule: {
    display: "flex",
    alignItems: "center",
    gap: { xs: 1, md: 1.4 },
    flexWrap: "nowrap",
  },
  titleRule: {
    flex: "1 1 auto",
    minWidth: { xs: 52, sm: 86, md: 164 },
    maxWidth: { xs: 116, sm: 170, md: 240 },
    height: { xs: 4, md: 5 },
    borderRadius: 999,
    alignSelf: "center",
    background:
      "linear-gradient(90deg, rgba(230,255,224,0.96) 0%, rgba(198,255,184,0.62) 52%, rgba(198,255,184,0.06) 100%)",
    boxShadow: "0 0 10px rgba(230,255,224,0.14)",
    transform: { xs: "translateY(3px)", md: "translateY(5px)" },
  },
  summary: {
    mt: { xs: 1.05, md: 2 },
    maxWidth: 760,
    color: "rgba(241,255,238,0.86)",
    fontSize: { xs: "0.7rem", md: "1rem" },
    lineHeight: { xs: 1.46, md: 1.8 },
  },
  accentRow: {
    mt: { xs: 1.65, md: 2.25 },
    display: { xs: "none", md: "grid" },
    gridTemplateColumns: "auto 1fr",
    columnGap: 1,
    rowGap: 0.35,
    alignItems: "center",
    color: "#E6FFE0",
  },
  availabilityDot: {
    width: 10,
    height: 10,
    borderRadius: "50%",
    bgcolor: "#E7FFE2",
    boxShadow: "0 0 0 4px rgba(231,255,226,0.08)",
  },
  chipWrap: {
    mt: { xs: 1.3, md: 3 },
    display: "flex",
    flexWrap: "wrap",
    gap: { xs: 0.5, md: 1 },
  },
  chip: {
    bgcolor: "rgba(245,255,242,0.12)",
    color: "#F6FFF3",
    border: `1px solid ${alpha("#ECFFE8", 0.18)}`,
    fontWeight: 700,
    height: { xs: 24, md: 34 },
    "& .MuiChip-label": {
      px: { xs: 0.78, md: 1.35 },
      fontSize: { xs: "0.6rem", md: "0.8rem" },
    },
  },
  ctaRow: {
    mt: { xs: 1.5, md: 3.5 },
    display: { xs: "grid", md: "flex" },
    gridTemplateColumns: { xs: "1.45fr 1fr 1.15fr", md: "none" },
    gap: { xs: 0.55, md: 1.5 },
    flexWrap: { md: "wrap" },
    alignItems: "stretch",
  },
  primaryBtn: {
    borderRadius: 999,
    px: { xs: 0.7, md: 2.5 },
    py: { xs: 0.72, md: 1.1 },
    textTransform: "none",
    fontWeight: 800,
    fontSize: { xs: "0.62rem", sm: "0.8rem", md: "0.9rem" },
    lineHeight: 1.18,
    textAlign: "center",
    background: "#F2FFF0",
    color: "#0E5A18",
    border: `1.5px solid ${alpha("#F2FFF0", 0.56)}`,
    boxShadow: `0 6px 16px ${alpha("#06210A", 0.12)}`,
    minWidth: 0,
    minHeight: { xs: 48, md: "auto" },
    width: { xs: "100%", md: "auto" },
    whiteSpace: { xs: "normal", md: "nowrap" },
    "&:hover": {
      background: "#E6FFE0",
      boxShadow: `0 8px 18px ${alpha("#06210A", 0.14)}`,
    },
    "& .MuiButton-endIcon": {
      ml: { xs: 0.32, sm: 0.6 },
      display: "inline-flex",
    },
    "& .MuiSvgIcon-root": {
      fontSize: { xs: "0.86rem", sm: "1rem" },
    },
  },
  secondaryBtn: {
    borderRadius: 999,
    px: { xs: 0.62, md: 2.2 },
    py: { xs: 0.68, md: 1.05 },
    textTransform: "none",
    fontWeight: 800,
    fontSize: { xs: "0.6rem", sm: "0.78rem", md: "0.88rem" },
    lineHeight: 1.18,
    textAlign: "center",
    color: "#F5FFF2",
    background: "rgba(255,255,255,0.05)",
    border: `1.5px solid ${alpha("#ECFFE8", 0.22)}`,
    minWidth: 0,
    minHeight: { xs: 48, md: "auto" },
    width: { xs: "100%", md: "auto" },
    whiteSpace: { xs: "normal", md: "nowrap" },
    "&:hover": {
      background: "rgba(255,255,255,0.1)",
    },
    "& .MuiButton-endIcon": {
      ml: { xs: 0.28, sm: 0.6 },
      display: "inline-flex",
    },
    "& .MuiSvgIcon-root": {
      fontSize: { xs: "0.84rem", sm: "1rem" },
    },
  },
  sideCard: {
    pointerEvents: "auto",
    borderRadius: 4,
    p: { xs: 1.05, sm: 2.4, md: 3.6 },
    background: { xs: "rgba(237,255,233,0.06)", sm: "rgba(255,255,255,0.96)" },
    border: { xs: "1px solid rgba(237,255,233,0.1)", sm: `1px solid ${alpha("#1CDB2F", 0.28)}` },
    boxShadow: {
      xs: "none",
      sm: `0 10px 24px ${alpha("#06210A", 0.08)}`,
    },
    display: "flex",
    flexDirection: "column",
    gap: { xs: 1.05, md: 2.5 },
    alignSelf: "center",
    justifySelf: "center",
    width: "100%",
    maxWidth: 460,
    position: "relative",
    overflow: "hidden",
  },
  sideUtility: {
    display: "inline-flex",
    alignItems: "center",
    gap: 0.65,
    alignSelf: "flex-start",
    px: 1.15,
    py: 0.65,
    borderRadius: 999,
    background: { xs: "rgba(237,255,233,0.06)", sm: "rgba(255,255,255,0.9)" },
    border: { xs: "1px solid rgba(237,255,233,0.12)", sm: `1px solid ${alpha("#1CDB2F", 0.2)}` },
    color: { xs: "#EAFEE5", sm: "#1A5D23" },
    fontSize: { xs: "0.66rem", sm: "0.72rem" },
    fontWeight: 900,
    letterSpacing: "0.12em",
    textTransform: "uppercase",
  },
  utilityDot: {
    width: 7,
    height: 7,
    borderRadius: "50%",
    bgcolor: "#1CDB2F",
    boxShadow: { xs: "0 0 0 3px rgba(28,219,47,0.12)", sm: "0 0 0 3px rgba(28,219,47,0.08)" },
  },
  contactCard: {
    p: { xs: 1.1, md: 1.6 },
    borderRadius: 3,
    background: { xs: "rgba(237,255,233,0.05)", sm: "rgba(255,255,255,0.96)" },
    border: { xs: "1px solid rgba(237,255,233,0.12)", sm: `1px solid ${alpha("#1CDB2F", 0.28)}` },
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 0.9,
  },
  contactMeta: {
    minWidth: 0,
    flex: 1,
  },
  contactTitle: {
    color: { xs: alpha("#F0FFEC", 0.7), sm: alpha("#23412A", 0.76) },
    fontSize: "0.7rem",
    fontWeight: 800,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  contactValue: {
    color: { xs: "#F5FFF2", md: DARK_GREEN },
    fontSize: { xs: "0.68rem", md: "0.8rem" },
    fontWeight: 700,
    whiteSpace: { xs: "normal", md: "nowrap" },
    overflow: "hidden",
    textOverflow: "ellipsis",
    lineHeight: { xs: 1.35, md: 1.4 },
  },
  contactAction: {
    borderRadius: 999,
    minWidth: 0,
    px: { xs: 0.9, md: 1 },
    py: { xs: 0.42, md: 0.5 },
    textTransform: "none",
    fontWeight: 800,
    fontSize: { xs: "0.62rem", md: "0.66rem" },
    whiteSpace: "nowrap",
    flexShrink: 0,
    color: { xs: "#0E5A18", sm: "#138B21" },
    borderColor: { xs: alpha("#F2FFF0", 0.56), sm: alpha("#1CDB2F", 0.38) },
    background: { xs: "#F2FFF0", sm: "transparent" },
    "&:hover": {
      borderColor: { xs: alpha("#F2FFF0", 0.72), sm: alpha("#1CDB2F", 0.52) },
      background: { xs: "#E6FFE0", sm: alpha("#1CDB2F", 0.06) },
    },
  },
  inlineValueRow: {
    mt: 0.3,
    display: "flex",
    alignItems: "center",
    gap: { xs: 0.28, md: 0.4 },
    minWidth: 0,
  },
  inlineCopyBtn: {
    width: 22,
    height: 22,
    minWidth: 22,
    minHeight: 22,
    borderRadius: 1,
    color: { xs: "#DDFED7", sm: "#1A8A25" },
    flexShrink: 0,
    p: 0,
    alignSelf: "center",
    "&:hover": {
      background: { xs: "rgba(237,255,233,0.08)", sm: alpha("#1CDB2F", 0.06) },
    },
  },
  qrBlock: {
    mt: 1.2,
    display: { xs: "none", sm: "flex" },
    justifyContent: "center",
    gap: { xs: 0.8, md: 1 },
    alignItems: "center",
    width: "fit-content",
    maxWidth: "100%",
    alignSelf: "center",
    mx: "auto",
    px: 0,
    py: { xs: 0.35, md: 0.45 },
    color: "inherit",
    textDecoration: "none",
    transition: "transform 160ms ease",
    "&:hover": {
      transform: "translateY(-1px)",
    },
  },
  qrMeta: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 0.35,
    maxWidth: { xs: 170, md: 190 },
    transform: { xs: "translateY(8px)", md: "translateY(10px)" },
  },
  qrLead: {
    color: "#179123",
    fontSize: { xs: "0.9rem", md: "1rem" },
    fontWeight: 800,
    lineHeight: 1.35,
  },
  qrText: {
    color: alpha("#23412A", 0.72),
    fontSize: { xs: "0.66rem", md: "0.72rem" },
    fontWeight: 500,
    lineHeight: { xs: 1.42, md: 1.5 },
  },
  qrTile: {
    width: { xs: 116, md: 138 },
    height: { xs: 116, md: 138 },
    flexShrink: 0,
    display: "grid",
    placeItems: "center",
    p: 0,
    borderRadius: 0,
    background: "transparent",
    border: "none",
    boxShadow: "none",
  },
  qrImage: {
    display: "block",
    width: "100%",
    height: "100%",
    objectFit: "contain",
  },
} as const;
