"use client";

import { alpha } from "@mui/material/styles";

export const BORDER_GREEN = alpha("#1CDB2F", 0.42);
export const DARK_GREEN = "#115419";
export const LABEL_GREEN = "#1CDB2F";
export const METRIC_GREEN = "#17B827";
export const AUTHOR_ICON_GREEN = "#168922";
export const TOOLTIP_BG = "#113416";
export const TOOLTIP_FG = "#E7FFE3";

export const SX = {
  section: {
    width: "100%",
    height: "100%",
    minHeight: "100%",
    position: "relative",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    pt: { xs: "calc(12px + env(safe-area-inset-top))", md: 2 },
    pb: { xs: "calc(82px + env(safe-area-inset-bottom))", md: 2 },
  },
  aura: {
    position: "absolute",
    inset: 0,
    pointerEvents: "none",
    background:
      "linear-gradient(135deg, rgba(255,255,255,0.02), rgba(255,255,255,0))",
    opacity: 0.14,
  },
  card: {
    position: "relative",
    zIndex: 1,
    width: "100%",
    maxWidth: { xs: 1120, sm: 980, md: 1120 },
    display: "flex",
    flexDirection: "column",
    borderRadius: { xs: 4, md: 6 },
    overflow: "hidden",
    background: "#FFFFFF",
    border: `1px solid ${BORDER_GREEN}`,
    boxShadow: "0 14px 34px rgba(15, 23, 42, 0.06)",
    maxHeight: {
      xs: "calc(100svh - 102px - env(safe-area-inset-top) - env(safe-area-inset-bottom))",
      md: "none",
    },
  },
  panel: {
    p: { xs: 1.4, sm: 2.2, md: 5 },
    display: "grid",
    gap: { xs: 1.3, sm: 2.1, md: 4 },
    gridTemplateColumns: {
      xs: "1fr",
      sm: "minmax(0, 1.04fr) minmax(228px, 0.78fr)",
      lg: "minmax(0, 1.3fr) minmax(280px, 0.7fr)",
    },
    alignItems: { xs: "stretch", sm: "center", lg: "center" },
    flex: 1,
    minHeight: 0,
    maxHeight: "100%",
    overflowX: "hidden",
    overflowY: "hidden",
    "@media (hover: none) and (pointer: coarse)": {
      overflowY: "auto",
      overscrollBehaviorY: "contain",
      WebkitOverflowScrolling: "touch",
      scrollbarWidth: "thin",
    },
  },
  thesisLabel: {
    fontSize: { xs: "0.68rem", md: "0.78rem" },
    fontWeight: 800,
    letterSpacing: "0.08em",
    color: "#0E4E13",
    mb: 1,
    textAlign: "left",
  },
  paperTitle: {
    fontWeight: 800,
    letterSpacing: "-0.015em",
    fontSize: { xs: "1.18rem", md: "1.82rem" },
    lineHeight: { xs: 1.12, md: 1.24 },
    color: "#16391B",
    textAlign: "left",
    maxWidth: 720,
  },
  authors: {
    mt: 0.6,
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    columnGap: 0.75,
    rowGap: 0.45,
    fontSize: { xs: "0.64rem", md: "0.78rem" },
    lineHeight: { xs: 1.26, md: 1.42 },
    color: "#111111",
    maxWidth: 720,
  },
  byPrefix: {
    color: "#111111",
    fontWeight: 500,
    fontSize: { xs: "0.64rem", md: "0.78rem" },
  },
  authorGroup: {
    display: "inline-flex",
    alignItems: "center",
    gap: { xs: 0.7, md: 0.45 },
    flexWrap: "nowrap",
  },
  authorName: {
    color: "#111111",
    fontWeight: 500,
    fontSize: { xs: "0.64rem", md: "0.78rem" },
  },
  authorSup: {
    ml: 0.1,
    fontSize: "0.72em",
    lineHeight: 1,
    verticalAlign: "super",
    color: "#111111",
    fontWeight: 600,
  },
  authorIconLink: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    color: AUTHOR_ICON_GREEN,
    textDecoration: "none",
    transition: "color 160ms ease, transform 160ms ease",
    "& .MuiSvgIcon-root": {
      fontSize: { xs: "0.82rem", md: "0.88rem" },
    },
    "&:hover": {
      color: DARK_GREEN,
      transform: "translateY(-1px)",
    },
  },
  authorSeparator: {
    color: "#111111",
  },
  summary: {
    color: alpha("#243226", 0.82),
    fontSize: { xs: "0.72rem", md: "0.9rem" },
    lineHeight: { xs: 1.5, md: 1.76 },
    textAlign: "justify",
    textJustify: "inter-word",
    maxWidth: 760,
  },
  summaryAccent: {
    textDecorationLine: "underline",
    textDecorationColor: alpha("#1CDB2F", 0.92),
    textDecorationThickness: "2px",
    textUnderlineOffset: "0.26em",
  },
  metricGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: { xs: 0.6, sm: 1.5 },
  },
  metricCard: {
    p: { xs: 0.72, sm: 1.5, md: 2 },
    borderRadius: 3,
    background: "#FFFFFF",
    border: `1px solid ${BORDER_GREEN}`,
    boxShadow: `0 6px 16px ${alpha("#1CDB2F", 0.08)}`,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
  },
  metricValue: {
    display: "block",
    fontWeight: 900,
    letterSpacing: "-0.03em",
    fontSize: { xs: "0.88rem", sm: "1.4rem", md: "1.54rem" },
    color: METRIC_GREEN,
    textShadow: "0 0 6px rgba(28, 219, 47, 0.12)",
  },
  metricLabel: {
    mt: 0.3,
    fontWeight: 600,
    fontSize: { xs: 8.25, sm: 12, md: 10 },
    letterSpacing: { xs: "0.04em", sm: "0.12em", md: "0.11em" },
    textTransform: "uppercase",
    color: "#084E10",
    textAlign: "center",
  },
  sideCard: {
    alignSelf: "stretch",
    borderRadius: 4,
    p: { xs: 1.3, sm: 2, md: 4 },
    background: "#FFFFFF",
    border: `1px solid ${BORDER_GREEN}`,
    boxShadow: `0 10px 24px ${alpha("#1CDB2F", 0.07)}`,
    color: "#154D1C",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    gap: { xs: 1.2, sm: 1.5, md: 3 },
    minHeight: { xs: "auto", lg: 404 },
  },
  sideLabel: {
    fontSize: { xs: 10, md: 11 },
    fontWeight: 900,
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    color: LABEL_GREEN,
  },
  journalTitle: {
    fontWeight: 700,
    fontSize: { xs: "0.8rem", md: "0.86rem" },
    lineHeight: { xs: 1.38, md: 1.56 },
    color: DARK_GREEN,
  },
  chipWrap: {
    display: "flex",
    flexWrap: "wrap",
    gap: { xs: 0.5, md: 1 },
  },
  chip: {
    bgcolor: "#FFFFFF",
    color: DARK_GREEN,
    border: `1px solid ${alpha("#1CDB2F", 0.5)}`,
    fontWeight: 700,
    height: { xs: 24, md: 32 },
    "& .MuiChip-label": {
      px: { xs: 0.8, md: 1.25 },
      fontSize: { xs: "0.62rem", md: "0.73rem" },
    },
  },
  actions: {
    display: "flex",
    gap: { xs: 0.7, sm: 0.85, md: 1.5 },
    flexWrap: "nowrap",
    alignItems: { xs: "center", sm: "stretch", md: "center" },
    flexDirection: { xs: "row", sm: "column", md: "row" },
  },
  primaryBtn: {
    position: "relative",
    borderRadius: 999,
    py: 0.82,
    textTransform: "none",
    fontWeight: 700,
    whiteSpace: "nowrap",
    minWidth: 0,
    flex: 1,
    px: { xs: 1.2, sm: 1.25, md: 1.8 },
    fontSize: { xs: "0.71rem", sm: "0.74rem", md: "0.76rem" },
    width: { sm: "100%", md: "auto" },
    color: "#FFFFFF",
    background: "#1CDB2F",
    border: `1.5px solid ${alpha("#1CDB2F", 0.62)}`,
    boxShadow: `0 6px 16px ${alpha("#1CDB2F", 0.1)}`,
    "& .MuiButton-endIcon": {
      ml: 0.6,
    },
    "& .MuiSvgIcon-root": {
      fontSize: "1rem",
    },
    "&:hover": {
      background: "#18C029",
      boxShadow: `0 8px 18px ${alpha("#1CDB2F", 0.12)}`,
    },
  },
  secondaryBtn: {
    borderRadius: 999,
    py: 0.82,
    textTransform: "none",
    fontWeight: 700,
    whiteSpace: "nowrap",
    minWidth: 0,
    flex: 1,
    px: { xs: 1, sm: 1.15, md: 1.8 },
    fontSize: { xs: "0.71rem", sm: "0.74rem", md: "0.76rem" },
    width: { sm: "100%", md: "auto" },
    color: DARK_GREEN,
    background: "#FFFFFF",
    border: `1.5px solid ${alpha("#1CDB2F", 0.5)}`,
    "& .MuiButton-startIcon": {
      mr: 0.6,
    },
    "& .MuiSvgIcon-root": {
      fontSize: "1rem",
    },
    "&:hover": {
      background: alpha("#1CDB2F", 0.08),
    },
  },
  qrLink: {
    mt: { xs: 1.7, md: 2.1 },
    display: { xs: "none", sm: "flex" },
    justifyContent: { sm: "flex-start", md: "center" },
    gap: { xs: 0.55, md: 0.75 },
    alignItems: "center",
    width: "fit-content",
    maxWidth: "100%",
    alignSelf: { sm: "flex-start", md: "center" },
    mx: { sm: 0, md: "auto" },
    borderRadius: 0,
    border: "none",
    background: "transparent",
    px: 0,
    py: 0,
    color: "inherit",
    textDecoration: "none",
    transition: "transform 160ms ease",
    "&:hover": {
      transform: "translateY(-1px)",
    },
  },
  qrCopy: {
    minWidth: 0,
    maxWidth: { xs: 145, sm: 120, md: 160 },
    transform: { xs: "translateY(8px)", sm: "translateY(4px)", md: "translateY(10px)" },
  },
  qrLead: {
    color: "#179123",
    fontSize: { xs: "0.9rem", md: "0.96rem" },
    fontWeight: 800,
    lineHeight: 1.35,
  },
  qrText: {
    mt: 0.28,
    fontSize: { xs: "0.66rem", md: "0.68rem" },
    lineHeight: { xs: 1.38, md: 1.42 },
    fontWeight: 500,
    color: alpha("#263A2A", 0.8),
  },
  qrTile: {
    width: { xs: 92, sm: 78, md: 114 },
    height: { xs: 92, sm: 78, md: 114 },
    flexShrink: 0,
    display: "grid",
    placeItems: "center",
    p: 0,
    borderRadius: 0,
    background: "transparent",
    border: "none",
    boxShadow: "none",
  },
  qrImage: {
    display: "block",
    width: "100%",
    height: "100%",
    objectFit: "contain",
  },
} as const;
